CREATE TABLE COMPLEX_DATA (
ID_CD INTEGER PRIMARY KEY,
TYPE_CD CHAR(1),
FILE_CD BYTEA,
CONSTRAINT validtype CHECK (upper(TYPE_CD) = 'I' OR upper(TYPE_CD) = 'S' OR 
upper(TYPE_CD) = 'M'));

-- CREATE TABLE IMG_FEATURES (
-- ID_FT INTEGER,
-- TYPE_FT CHAR (1),
-- CD_REF INTEGER,
-- PRIMARY KEY (ID_FT, TYPE_FT),
-- CONSTRAINT ID_FK FOREIGN KEY (CD_REF) REFERENCES COMPLEX_DATA (ID_CD));

CREATE TABLE SHAPE (
ID_FT INTEGER PRIMARY KEY,
CD_REF INTEGER,
IS_FOCUS BOOLEAN DEFAULT 'FALSE',
FEATURE FLOAT8[],
CONSTRAINT CD_FK FOREIGN KEY (CD_REF) REFERENCES COMPLEX_DATA (ID_CD)
ON DELETE CASCADE ON UPDATE CASCADE); 

CREATE TABLE COLOR (
ID_FT INTEGER PRIMARY KEY,
CD_REF INTEGER,
IS_FOCUS BOOLEAN DEFAULT 'FALSE',
FEATURE FLOAT8[],
CONSTRAINT CD_FK FOREIGN KEY (CD_REF) REFERENCES COMPLEX_DATA (ID_CD)
ON DELETE CASCADE ON UPDATE CASCADE); 

CREATE TABLE TEXTURE (
ID_FT INTEGER PRIMARY KEY,
CD_REF INTEGER,
IS_FOCUS BOOLEAN DEFAULT 'FALSE',
FEATURE FLOAT8[],
CONSTRAINT CD_FK FOREIGN KEY (CD_REF) REFERENCES COMPLEX_DATA (ID_CD)
ON DELETE CASCADE ON UPDATE CASCADE); 

CREATE TABLE SHAPE_F_BASE(
ID_FOCUS INTEGER,
ID_FEATURE INTEGER,
DIST_L1 FLOAT8,
DIST_L2 FLOAT8,
DIST_LINF FLOAT8,
PRIMARY KEY (ID_FOCUS, ID_FEATURE),
CONSTRAINT SHAPEFOCUS_FK FOREIGN KEY (ID_FOCUS) REFERENCES SHAPE (ID_FT)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT SHAPEFEATURE_FK FOREIGN KEY (ID_FEATURE) REFERENCES SHAPE(ID_FT)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE COLOR_F_BASE(
ID_FOCUS INTEGER,
ID_FEATURE INTEGER,
DIST_L1 FLOAT8,
DIST_L2 FLOAT8,
DIST_LINF FLOAT8,
PRIMARY KEY (ID_FOCUS, ID_FEATURE),
CONSTRAINT COLORFOCUS_FK FOREIGN KEY (ID_FOCUS) REFERENCES COLOR (ID_FT)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT COLORFEATURE_FK FOREIGN KEY (ID_FEATURE) REFERENCES COLOR(ID_FT)
ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE TEXTURE_F_BASE(
ID_FOCUS INTEGER,
ID_FEATURE INTEGER,
DIST_L1 FLOAT8,
DIST_L2 FLOAT8,
DIST_LINF FLOAT8,
PRIMARY KEY (ID_FOCUS, ID_FEATURE),
CONSTRAINT TEXTUREFOCUS_FK FOREIGN KEY (ID_FOCUS) REFERENCES TEXTURE (ID_FT)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT TEXTUREFEATURE_FK FOREIGN KEY (ID_FEATURE) REFERENCES TEXTURE(ID_FT)
ON DELETE CASCADE ON UPDATE CASCADE);